service: operativaApi #Name of your App

provider:
 name: aws
 vpc:
   securityGroupIds:
     - sg-e2552c9e
   subnetIds:
     - subnet-b1e2efcb
 runtime: nodejs12.x # Node JS version
 memorySize: 512
 timeout: 15
 stage: prod
 region: us-east-2 # AWS region

package:
#  include:
#    - include-me.js
#    - include-me-dir/**
  exclude:
    - .env

functions:
 api:
   handler: lambda.handler
   events:
     - http: ANY {proxy+}
     - http: ANY /